backend:
  name: github
  repo: mondinellisg-prog/web-nancy
  branch: main
  base_url: https://sveltia-auth-proxy.tu-usuario.workers.dev # TU URL DEL WORKER SIN EL /callback
  
media_folder: "optm"
public_folder: "optm"

collections:
  - name: "contenido"
    label: "Administrar Web"
    files:
      - name: "data"
        label: "Datos del Sitio"
        file: "data.json"
        fields:
          # --- HERO (PORTADA) ---
          - name: "hero"
            label: "1. Encabezado"
            widget: "object"
            collapsed: true
            fields:
              - {label: "Título", name: "hero_title", widget: "string"}
              - {label: "Descripción", name: "hero_desc", widget: "string"}

          # --- OBRAS ---
          - name: "obras"
            label: "2. Galería de Obras"
            widget: "list"
            collapsed: false
            summary: "{{title}}"
            fields:
              - {label: "Título de la Obra", name: "title", widget: "string"}
              - {label: "Técnica", name: "tech", widget: "string", required: false}
              - {label: "Foto de la Obra", name: "image", widget: "image"}

          # --- TALLERES ---
          - name: "talleres"
            label: "3. Cursos y Talleres"
            widget: "list"
            collapsed: true
            summary: "{{title}}"
            fields:
              - {label: "Nombre del Taller", name: "title", widget: "string"}
              - {label: "Descripción", name: "desc", widget: "text"}
              - {label: "Imagen del Taller", name: "image", widget: "image"}
