backend:
  name: github
  repo: mondinellisg-prog/web-nancy
  branch: main
  base_url: https://sveltia-auth-proxy.tu-usuario.workers.dev # TU URL DEL WORKER SIN EL /callback
  
media_folder: "optm"
public_folder: "optm"

collections:
  - name: "config"
    label: "Contenido de la Web"
    files:
      - name: "landing"
        label: "Página Principal"
        file: "data.json"
        fields:
          - { label: "Título Hero", name: "hero_title", widget: "string" }
          - { label: "Descripción Hero", name: "hero_desc", widget: "text" }
          
          - name: "obras"
            label: "Galería de Cuadros"
            widget: "list"
            fields:
              - { label: "Título", name: "title", widget: "string" }
              - { label: "Técnica", name: "tech", widget: "string" }
              - { label: "Foto", name: "image", widget: "image" }

          - name: "talleres"
            label: "Cursos y Talleres"
            widget: "list"
            fields:
              - { label: "Nombre Taller", name: "title", widget: "string" }
              - { label: "Descripción", name: "desc", widget: "text" }
              - { label: "Imagen", name: "image", widget: "image" }
